import "bootstrap/dist/css/bootstrap.min.css";
import { ThemeProvider } from "next-themes";
import { Cairo } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/sharedcomponent/navbar";
import Footer from "./sharedcomponent/footer";

const cairo = Cairo({
  subsets: ["arabic"],
  weights: ["300", "400", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
